import '../../JUSTFILE'

ROOT := `cd ../.. && pwd`

alias i := install

_:
    just --list

[doc]
fmt:
    deno fmt
    just --fmt

[script('bash')]
home:
    cd {{ ROOT }}
    OPEN_FOLDER_IN_EDITOR="{{ OPEN_FOLDER_IN_EDITOR }}"
    $OPEN_FOLDER_IN_EDITOR .

# ## scripts
[script('bash')]
install:
    deno install --allow-scripts

[script('bash')]
gql *args='':
    deno run --allow-all \
    npm:@graphql-codegen/cli/graphql-codegen-esm \
    --config=./codegen.ts {{ args }}

# ## main
start:
    deno run -A main.ts

dev:
    deno run -A --watch-hmr main.ts
