type ApiKey {
  _id: ID!
  bucket: Bucket!
  bucket_id: ID!
}

type Bucket {
  """It should be the same as email"""
  _id: ID!
  email: String!
  keys: [ApiKey!]!
  user: User!
  user_id: ID!
}

interface Session {
  _id: ID!
  created_at: String!
  updated_at: String!
}

type SessionGhost implements Session {
  _id: ID!
  created_at: String!
  updated_at: String!
}

type SessionNormal implements Session {
  _id: ID!
  active_bucket: Bucket
  active_bucket_id: ID
  created_at: String!
  updated_at: String!
  user: User!
  user_id: ID!
}

type User {
  _id: ID!
  buckets: [Bucket!]!
  sessions: [SessionNormal!]!
}