import '../../JUSTFILE'

ROOT := `cd ../.. && pwd`

alias i := install

_:
    just --list

[script('bash')]
fmt:
    just --fmt
    deno fmt

[script('bash')]
home *args="":
    cd {{ ROOT }}
    OPEN_FOLDER_IN_EDITOR="{{ OPEN_FOLDER_IN_EDITOR }}"
    {{ if args == "cd" { "$OPEN_FOLDER_IN_EDITOR ." } else { args } }}

[script('bash')]
install:
    deno install --allow-scripts

gql:
    deno run --allow-all npm:@graphql-codegen/cli/graphql-codegen-esm
