import '../JUSTFILE'

ROOT := `cd .. && pwd`

alias i := install

_:
    just --list

[script('bash')]
fmt:
    just --fmt
    deno fmt

[script('bash')]
install:
    deno install --allow-scripts

gql:
    deno run --allow-all npm:@graphql-codegen/cli/graphql-codegen-esm --config core/codegen/config.ts

[script("bash")]
start port="3000":
    PORT={{ port }} deno run -A main.ts
